name: Reusable Deploy
on:
  workflow_call:
    inputs:
      artifact-name: #given name
        description: The name of the deployable artifact files
        required: false
        default: dist
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get build
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Output info
        run: echo "Deploying & uploading..."
